### ISSUE TITLE
这两个值要设置为多少 ？ --first-brc20-height， --first-inscription-height

### ISSUE THREAD

**Issue by Rodert** [okx/ord#26]
是这样吗？
```
--first-brc20-height=726731 --first-inscription-height=826731 
```

**Comment by Rodert** [comment]
779832 ordi 第一个块

**Comment by wanyvic** [comment]
In general, you do not need to set the parameters because they will be assigned by default. For more information, follow this code:
https://github.com/okx/ord/blob/05b0f5eee912b831cfc1a619c84c75e939feaf40/src/chain.rs#L41-L57

**Comment by Rodert** [comment]
> 一般情况下，您不需要设置这些参数，因为它们会被默认分配。欲了解更多信息，请关注此代码：
> 
> https://github.com/okx/ord/blob/05b0f5eee912b831cfc1a619c84c75e939feaf40/src/chain.rs#L41-L57

i see, thanks. i am debug okx-by-ord，this is full project ? you konw .
