### ISSUE TITLE
我想使用铭文和brc20接口，启动节点是从0区块开始索引，这正常吗？内存需要多少g？

### ISSUE THREAD

**Issue by guo2410** [okx/ord#32]

**Comment by dubuqingfeng** [comment]
正常的，需要历史的 utxo 数据，大概需要3天左右，目前跑的同步正常的内存需要大概50G（有 cache），提供正常业务在使用

**Comment by guo2410** [comment]
> 正常的，需要历史的 utxo 数据，大概需要3天左右，目前跑的同步正常的内存需要大概50G（有 cache），提供正常业务在使用

用的啥命令呢？我一天只能同步一两万个块

**Comment by guo2410** [comment]
solve

**Comment by godeepcode** [comment]
@guo2410 @dubuqingfeng  请问你们是什么命令跑的节点、用的服务器配置怎样，我这跑的节点同步速度很慢(用okx的快照，20小时才同步1000个块)

**Comment by dubuqingfeng** [comment]
> @guo2410 @dubuqingfeng 请问你们是什么命令跑的节点、用的服务器配置怎样，我这跑的节点同步速度很慢(用okx的快照，20小时才同步1000个块)

cache 会改大一点

**Comment by godeepcode** [comment]
> > @guo2410 @dubuqingfeng 请问你们是什么命令跑的节点、用的服务器配置怎样，我这跑的节点同步速度很慢(用okx的快照，20小时才同步1000个块)
> 
> cache 会改大一点

@dubuqingfeng 再请教下，这个 cache 是对应有命令参数设置还是指的是服务器的内存？我现在服务器配置是aws ec2 7i.2xlarge(8核16GB内存)
